backend:
  name: git-gateway

media_folder: "images" # Folder where user uploaded files should go
public_folder: "images"
publish_mode: "editorial_workflow" # see https://www.netlifycms.org/docs/open-authoring/

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "published", widget: "date" }
      - { label: "Intro Blurb", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - label: "Align Content"
        name: "author"
        widget: "select"
        options: ["Dillon Kearns"]
        default: "Dillon Kearns"
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Type",
          name: "type",
          widget: "hidden",
          default: "blog",
          required: false,
        }
